# Generated by Django 4.2.6 on 2023-10-26 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('capa', models.TextField(blank=True, null=True)),
                ('title', models.TextField()),
                ('year', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
