# Generated by Django 4.2.5 on 2023-11-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
