# Generated by Django 4.2.5 on 2023-11-07 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0002_filme_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filme',
            name='duration',
        ),
    ]
