# Generated by Django 4.2.6 on 2023-11-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0003_remove_filme_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
