# Generated by Django 4.2.6 on 2023-11-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmes', '0004_filme_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='ratings',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
